version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: echo 'export PATH=${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin' >> $BASH_ENV
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn-with-greenkeeper
          command: |
            sudo yarn global add greenkeeper-lockfile@1
            yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
      - run: greenkeeper-lockfile-update
      - run: npm run lint
      - run: npm run build_all
      - run: npm run check_circular_dependencies
      - run: npm run cover
      - run:
          name: test-coverage
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - run: greenkeeper-lockfile-upload

  deploy:
    docker:
      - image: circleci/node:6
    steps:
      - deploy:
          name: npm
          command: sh tools/publish.sh

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-(alpha|beta)\.[0-9]+)?/
            branches:
              ignore: /.*/
notify:
  webhooks:
    - url: http://teambition.vvlyn.com/api/circle
